movieratings/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^profile/$', views.profile, name='profile')
]

movieratings/lensview/urls.py
from django.conf.urls import url
from . import views


app_name = 'lensview'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^top_movies/$', views.top_movies, name='top_movies'),
    url(r'^movies/(?P<movie_id>\d+)$', views.show_movie, name='movie_detail'),
    url(r'^raters/(?P<pk>\d+)$', views.RaterDetailView.as_view(), name='rater_detail'),
    url(r'^register/$', views.register, name='register'),
    url(r'^new/$', views.new, name='new')
]

movieratings/movieratings/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^lensview/', include('lensview.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls'))
]

movieratings/accounts/models.py
from django.db import models

# Create your models here.

movieratings/lensview/models.py
from django.db import models
from django.db.models import Avg, Sum
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError



class Movie(models.Model):
    title = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)
    number_ratings = models.IntegerField(default=-1)
    rating_sum = models.IntegerField(default=-1)
    average_rating = models.FloatField()


    def __str__(self):
        return self.title


class Rater(models.Model):

    GENDER_CHOICES = (('M', 'Male'),
                    ('F', 'Female')
                    )

    AGE_CHOICES = ((1, 'Under 18'),
                (18, '18-24'),
                (25, '25-34'),
                (35, '35-44'),
                (45, '45-49'),
                (50, '50-55'),
                (56, '56+')
                )

    OCCUPATION_CHOICES = ((0, "Other"),
                        (1, "Academic/Educator"),
                        (2, "Artist"),
                        (3, "Clerical/Admin"),
                        (4, "College/Grad Student"),
                        (5, "Customer Service"),
                        (6, "Doctor/Health Care"),
                        (7, "Executive/Managerial"),
                        (8, "Farmer"),
                        (9, "Homemaker"),
                        (10, "K-12 Student"),
                        (11, "Lawyer"),
                        (12, "Programmer"),
                        (13, "Retired"),
                        (14, "Sales/Marketing"),
                        (15, "Scientist"),
                        (16, "Self-employed"),
                        (17, "Technician/Engineer"),
                        (18, "Tradesman/Craftsman"),
                        (19, "Unemployed"),
                        (20, "Writer")
                        )

    age = models.IntegerField(choices=AGE_CHOICES)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    occupation = models.IntegerField(choices=OCCUPATION_CHOICES)
    zipcode = models.CharField(max_length=10)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)


    def __str__(self):
        return str(self.id)


class Rating(models.Model):
    rater = models.ForeignKey('Rater')
    movie = models.ForeignKey('Movie')
    stars = models.IntegerField()

    def __str__(self):
        return 'Rating(id={}, rater={}, stars={}, movie={})'.format(
            self.id, self.rater, self.stars, self.movie)

movieratings/lensview/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Rating

from .models import Rater

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('movie', 'stars')

movieratings/accounts/views.py
from django.shortcuts import render
from lensview.models import Rater, Rating, Movie
from django.contrib.auth.models import User

def profile(request):
    rater = Rater.objects.get(user_id=request.user.id)
    ratings = rater.rating_set.all()
    return render(request, 'accounts/profile.html', {'rater': rater, 'ratings': ratings})

movieratings/lensview/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Movie, Rater, Rating
from .forms import UserForm, RatingForm
from django.views.generic.detail import DetailView


def index(request):
    return render(request, "lensview/index.html")


def detail(request, movie_id):
    return HttpResponse("You're looking at movie %s." % movie_id)


def top_movies(request):
    significantly_rated = Movie.objects.filter(number_ratings__gte=300)
    top_twenty = significantly_rated.order_by('average_rating').reverse()[:20]
    return render(request, 'lensview/top_movies.html', {'top_twenty': top_twenty})


def show_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    ratings = movie.rating_set.all()
    rating_list = Rating.objects.filter(movie_id=movie.id)
    rater_queries = rating_list.values_list('rater_id', flat=True)
    return render(request, 'lensview/movie.html', {'movie': movie, 'ratings': ratings, 'rater_queries': rater_queries})


# def show_rater(request, rater_id):
#     rater = get_object_or_404(Rater, pk=rater_id)
#     ratings = rater.rating_set.all()
#     return render(request, 'lensview/rater.html', {'rater': rater, 'ratings': ratings})


class RaterDetailView(DetailView):
    model = Rater

    def get_context_data(self, **kwargs):
        context = super(RaterDetailView, self).get_context_data(**kwargs)
        context['ratings'] = self.object.rating_set.all()
        return context


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print (user_form.errors)
    else:
        user_form = UserForm()
    return render(request,
            'registration/register.html',
            {'user_form': user_form, 'registered': registered} )


def new(request):
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rater = Rater.objects.get(user=request.user)
            rating.rater = rater
            rating.save()
            return HttpResponseRedirect('/lensview/')
    else:
        form = RatingForm()
    return render(request, 'lensview/new.html', {'form': form})

movieratings/accounts/templates/accounts/profile.html
{% extends "lensview/base.html" %}
{% load i18n %}


{% block content %}

{% if request.user.is_authenticated %}

<p></p>

  <h3><u>Your user information</u></h3>
    <b>Username:</b> {{request.user.username}}<br>
    <b>Age:</b> {{ rater.get_age_display }}<br>
    <b>Gender:</b> {{ rater.gender }}<br>
    <b>Occupation:</b> {{ rater.get_occupation_display }}<br>

    <p>You have rated <b>{{ ratings | length }}</b> movies.</p>

    <h3><u>Your Movie Ratings</u></h3>

    {% for rating in ratings %}
    <p>
      <b>Stars:</b> &nbsp;&nbsp; {{ rating.stars }} &nbsp;&nbsp; for &nbsp;&nbsp; <a href="{% url 'lensview:movie_detail' rating.movie.pk %}">{{ rating.movie }}</a>
    </p>
  {% endfor %}

{% else %}
you are not logged in, please <a href="{% url login %}">login</a>

{% endif %}

{% endblock content %}

movieratings/lensview/templates/lensview/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
​

{% block title %}{{ title }} {{ site_title|default:_("Movie Lens") }}

{% if request.user.is_anonymous %}
&nbsp;&nbsp; | &nbsp;&nbsp; <a href="{% url 'login' %}">Login</a>
{% endif %}
&nbsp;&nbsp; | &nbsp;&nbsp; <a href="{% url 'lensview:index' %}">Home</a>

{% if request.user.is_authenticated %}
&nbsp;&nbsp; | &nbsp;&nbsp;  user: <b>{{request.user.username}}</b>
&nbsp;&nbsp; | &nbsp;&nbsp;  <a href="/lensview/new/">Add New Rating</a>
&nbsp;&nbsp; | &nbsp;&nbsp;  <a href="/accounts/profile/">Profile</a>
&nbsp;&nbsp; | &nbsp;&nbsp;  <a href="{% url 'logout' %}">Logout</a>
{% else %}
&nbsp;&nbsp; | &nbsp;&nbsp;  Not logged in.
{% endif %}
{% endblock %}
{% block branding %}
{% endblock %}

{% block nav-global %}{% endblock %}

    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h2>You have logged out</h2>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>

</html>

movieratings/lensview/templates/lensview/index.html
{% extends "lensview/base.html" %}
{% load i18n %}

{% block content %}
  <h1>Welcome to Movie Lens</h1>
  {% if request.user.is_anonymous %}
    <a href="/login/">Login Here</a><br>
    <a href="/lensview/register/">Register Here</a><br>
  {% endif %}
  <a href="/lensview/top_movies">See Top 20 Movies</a>
{% endblock content %}

movieratings/lensview/templates/lensview/movie.html
{% extends "lensview/base.html" %}
{% load i18n %}

{% block content %}
  <h2><u>{{ movie.title }}</u></h2>
  {% if request.user.is_authenticated %}
    {% if user.rater.id not in rater_queries %}
      You have not rated this movie yet<br>
      <a href="/lensview/new/">Add New Rating</a><br>
    {% else %}
      You have already rated this movie
    {% endif %}
  {% endif %}
    <p>
      <b>Number of ratings:</b> &nbsp;&nbsp; {{ movie.number_ratings }}<br>
      <p></p>
      <b>Average rating:</b> &nbsp;&nbsp; {{ movie.average_rating | floatformat:"2" }}
    </p>

    <h3><u>Ratings</u></h3>

    {% for rating in ratings %}
    <p>
      <b>Stars:</b> &nbsp;&nbsp; {{ rating.stars }} &nbsp;&nbsp;&nbsp;&nbsp; <b>Rater:</b> &nbsp;&nbsp; <a href="{% url 'lensview:rater_detail' rating.rater.pk %}">#{{ rating.rater }}</a>
    </p>

    {% endfor %}
{% endblock content%}

movieratings/lensview/templates/lensview/new.html
{% extends "lensview/base.html" %}
{% load i18n %}
{% block content %}
<h2>Add a new rating</h2>
User: {{ request.user.username }}
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <input type="submit" name="submit" value="Create New Movie Rating">
</form>
{% endblock content %}

movieratings/lensview/templates/lensview/rater.html
{% extends "lensview/base.html" %}
{% load i18n %}
{% block content %}
  <h2><u>Rater #{{ rater.id }}</u></h2>
  <p>
    <b>Age:</b> {{ rater.get_age_display }}<br>
    <b>Gender:</b> {{ rater.gender }}<br>
    <b>Occupation:</b> {{ rater.get_occupation_display }}<br>
  </p>
    This rater has rated <b>{{ ratings | length }}</b> movies.

    <h3><u>Movie Ratings</u></h3>

    {% for rating in ratings %}
    <p>
      <b>Stars:</b> &nbsp;&nbsp; {{ rating.stars }} &nbsp;&nbsp; for &nbsp;&nbsp; <a href="{% url 'lensview:movie_detail' rating.movie.pk %}">{{ rating.movie }}</a>
    </p>
  {% endfor %}
{% endblock content %}

movieratings/lensview/templates/lensview/rater_detail.html
{% extends "lensview/base.html" %}
{% load i18n %}
{% block content %}
  <h2><u>Rater #{{ rater.id }}</u></h2>
  <p>
    <b>Age:</b> {{ rater.get_age_display }}<br>
    <b>Gender:</b> {{ rater.gender }}<br>
    <b>Occupation:</b> {{ rater.get_occupation_display }}<br>
  </p>
    This rater has rated <b>{{ ratings | length }}</b> movies.

    <h3><u>Movie Ratings</u></h3>

    {% for rating in ratings %}
    <p>
      <b>Stars:</b> &nbsp;&nbsp; {{ rating.stars }} &nbsp;&nbsp; for &nbsp;&nbsp; <a href="{% url 'lensview:movie_detail' rating.movie.pk %}">{{ rating.movie }}</a>
    </p>
  {% endfor %}
{% endblock content %}

movieratings/lensview/templates/lensview/top_movies.html
{% if top_twenty %}
  <h1>20 Top Rated Movies</h1>
    <ol>
      {% for movie in top_twenty %}
       <li><a href="{% url 'lensview:movie_detail' movie.pk %}">{{movie.title}}</a></li>
       Average Rating: {{movie.average_rating | floatformat:"2"}}
       <p></p>
      {% endfor %}
    </ol>
    {% else %}
      <p>No top movies to display</p>
{% endif %}